name: GitBook

on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - CMakeLists.txt
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: fkirc/skip-duplicate-actions@master
    - run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: sudo npm install -g --unsafe-perm gitbook-cli gitbook-summary svgexport
    - uses: actions/checkout@v2
    - run: gitbook install
    - run: gitbook build
    - run: gitbook pdf . _book/teo-developer-manual.pdf
    - run: gitbook mobi . _book/teo-developer-manual.mobi
    - run: gitbook epub . _book/teo-developer-manual.epub
    - uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: _book
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
